### ISSUE TITLE
make unit tests deterministic

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpfit#33]
unit tests should use fixed seeds to prevent non-determinism associated with initial guesses etc.

For example, this error seems to be sporadic, some times it passes, sometimes it fails:

> ======================================================================
FAIL [0.000s]: test_rms_error (gpfit.tests.t_ex6_3.t_ex6_3_ISMA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home1/jenkins/workspace/gpfit_PullRequest/buildnode/reynolds/gpfit/tests/t_ex6_3.py", line 21, in test_rms_error
    self.assertTrue(self.rms_error < 5e-4)
AssertionError: False is not true

**Comment by galbramc** [comment]
Here is another one that sporadically fails

```
======================================================================
ERROR [5.227s]: test_hoburgabbeel_ex6_1_ (gpfit.tests.t_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jenkins/workspace/gpfit_PullRequest/buildnode/macys_ElCap/venv2_gpfit/lib/python2.7/site-packages/gpkit/tests/helpers.py", line 51, in test
    logged_example_testcase(name, import_dict, path)(self)
  File "/Users/jenkins/workspace/gpfit_PullRequest/buildnode/macys_ElCap/venv2_gpfit/lib/python2.7/site-packages/gpkit/tests/helpers.py", line 70, in test
    getattr(self, name)(imported[name])
  File "/Users/jenkins/workspace/gpfit_PullRequest/buildnode/macys_ElCap/gpfit/tests/t_examples.py", line 32, in test_hoburgabbeel_ex6_1
    self.assertTrue(example.errorSMA < 1e-4)
AssertionError: False is not true
```

**Comment by whoburg** [comment]
also re-enable example output diff in Jenkins, see #52

**Comment by pgkirsch** [comment]
Closed by #105
