### ISSUE TITLE
Bug when K==1

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpfit#50]
near line 156 of `fit.py`, `cstrt = MonomialEquality(cstrt, "=", 1)` should I think be be `cstrt = (mono == posy)`?

**Comment by mayork** [comment]
just ran into the same problem...I think this is causing the following error

```
Traceback (most recent call last):
  File "/Users/mayork/Documents/GpGit/gpfit/gpfit/fan_map_spine_fitting.py", line 52, in <module>
    r,const = fit.fit(independent, dependent, 1, 'SMA')
  File "/Users/mayork/Documents/GpGit/gpfit/gpfit/fit.py", line 165, in fit
    cstrt = MonomialEquality(cstrt, "=", 1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/nomials/nomial_math.py", line 594, in __init__
    ScalarSingleEquationConstraint.__init__(self, left, oper, right)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/nomials/nomial_math.py", line 435, in __init__
    self).__init__(Signomial(left), oper, Signomial(right))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/nomials/nomial_math.py", line 73, in __init__
    assert len(cs) == len(exps)
TypeError: object of type 'int' has no len()
```

**Comment by bqpd** [comment]
I believe this was fixed in the recent refactor.
